### ISSUE TITLE
Need to support deep comparison.

### ISSUE THREAD

**Issue by janryWang** [mweststrate/immer#143]
Hello, I am very happy to see exciting projects like immer that help us to manipulate data more conveniently and safely. However, I found that the problem is that immersed in data manipulation only makes shallow comparisons. This can cause duplicate rendering problems in React rendering. So, can immer support depth comparison? 
  
you can use this library.  https://github.com/FormidableLabs/react-fast-compare

```
import produce from "immer"

const aa = {
   mm:[
     {name:"123"}
   ]
}

let kk = produce(aa,(state)=>{
  state.mm[0] = {name:"123"}
})

console.log(kk === aa) //Expected result : true

```

**Comment by janryWang** [comment]
@mweststrate I hope this "is" function replace to deep equal function(https://github.com/FormidableLabs/react-fast-compare). https://github.com/mweststrate/immer/blob/master/src/proxy.js#L79

**Comment by mweststrate** [comment]
In general there should not much need to do so when relying on immutability
in the first place. The whole idea is that you want to avoid deep equal
checks by using immutable, structurally shared data structures so that you
can rely on pointer equality. In the few cases where you can't do so, you
can do the deep equal check in userland code before making the assignment

Op zo 22 apr. 2018 om 11:11 schreef Janry <notifications@github.com>:
