### ISSUE TITLE
README: Imperative programming

### ISSUE THREAD

**Issue by guillaumearm** [mweststrate/immer#188]
Hi, this is a nice little library :) 

It would be nice to have a section in the readme talking about the fact `immer` encourage `imperative programming` over `declarative programming`.

What do you think about that ?

**Comment by andrew-aladev** [comment]
Immer provides a dirty hack that add ability to use imperative api instead of declarative. As a result many applications wants users to provide **changes only** instead of `full property value`. This hack works as a bridge between declarative and imperative programming.

The problem is that this hack forces user to provide a way of converting declarative application to imperative instead of application authors. [This issue](https://github.com/ianstormtaylor/slate/issues/3699) will be an example.

```js
<Slate document={document} />
```

User is not able to provide new document to editor: slate is waiting for **changes only**. So slate user have to provide that changes himself: new input value -> find minimal changes required to make new document from prev document -> fight with DSU, etc -> provide changes.

I will warn react developers that his main declarative approach is not working anymore - users invented dirty hacks.
