### ISSUE TITLE
Clarification about documentation

### ISSUE THREAD

**Issue by davidmal200** [mweststrate/immer#201]
I want to ask clarification about documentation.

In pitfalls section you state:

>  That is, no object should appear twice in the tree, and there should be no circular references.

Can you explain what you mean? For example if I had state like

```
myState = {
items: [{itemID:1}, {itemID:2}, {itemID:3}]
filteredItems:[]
}
```

and then say `filteredItems `would store all items from `items `except say items with ID 3, would that violate the sentence I cited from your docs? Because in that case say **same** objects (objects without ID 3) would be stored **both** under key `items `and under key `filteredItems`.

e.g if I computed next state as:
```

nextState = produce(myState, (draft)=>{
 draft.filteredItems= draft.items.filter(x=>x.itemID!=3)
})
```

**Comment by mweststrate** [comment]
Correct, that violates the rule indeed, as  your state is no longer a directed acyclic tree. Simple rule of thumb: if `JSON.parse(JSON.stringify(state))` produces not the same thing, your state is not a tree.

Since your items have id's already, just store the ID's in `filteredItems`. (And turn `items` into a key/value map for fast lookups). 

That being said, storing `filterItems` in your state is imho an anti pattern; information that can be derived doesn't need to be stored in the state. It prevents bugs where you add for example an item to `items` but forget to update `filteredItems` as well

**Comment by mweststrate** [comment]
@davidmal200 no, cloning will change the structure of your state in your example, simple demonstration:

```javascript
const x = { id: 1, text: "hello" }
const items = { items: [x], filteredItems: [x] }
items.items[0].text = "hello2"
items.filteredItems[0].text
// 'hello2' (correct)

items2 = JSON.parse(JSON.stringify(items))
items2.items[0].text = "hello"
items2.filteredItems[0].text
// 'hello2' (incorrect)
```

You serialized a graph, but you got back a tree; and your filtered items are now inconsistent with your items. One of the core principles of Redux for example is that the state must be a [tree](https://redux.js.org/introduction/threeprinciples#single-source-of-truth) as doing otherwise will break assumptions other tools make on your state, not just Immer, but also Redux or React devtools etc etc. I'm pretty sure there is quite some literature online covering why the state should be organized as tree, and what some best practices are around designing state trees.

**Comment by davidmal200** [comment]
@mweststrate Ah do you mean in `items2` now the `filteredItems` doesn't have the reference to `[x]`? 
Although content wise both `items2` and `items` are same right?

**Comment by mweststrate** [comment]
Yes, but semantics are different, first you got one object, now you got
two. Checks for reference equality will fail in `items2`, etc

Op ma 24 sep. 2018 om 10:00 schreef davidmal200 <notifications@github.com>:

**Comment by davidmal200** [comment]
Yes `items2.items[0] !== items2.filteredItems[0]` while `items.items[0] == items.filteredItems[0]`. You mean that right?

I would still suggest you add such examples in Pitfalls section as it would be more clear what is allowed and what not. There is also some restriction on dates I remember small code examples wouldn't hurt there either.

Thanks.

**Comment by mweststrate** [comment]
if a small PR could elaborate on it, that would be welcome, (ideally providing a good external link). But explaining these concepts are kinda outside the scope of immer, immer is tool you might pick because it is useful when opting for an immutable state tree architecture. But explaining why that is a good architecture or understanding the rules of that game are kinde outside of Immer, as typically you answered those first. 

One uses Immer as _result_ of the architecture choice (like Redux, or React-copy-on-write, bey etc). If using immer influences your state tree design, then you are using immer either for the wrong reason, or you didn't think the design through. In your case specific I would first take a second look at at how the design your state shape, as your current setup is quite unidiomatic. Googling for something like "designing immutable state tree" or "redux store structure best practice"  or something like that will probably lead you to something useful that sheds some light on the background of immutable state trees.

**Comment by mweststrate** [comment]
Yeah, as said, PR is welcome :-) if there is way of expressing this that
would have made this more clear to you

Op ma 24 sep. 2018 om 10:26 schreef davidmal200 <notifications@github.com>:

**Comment by davidmal200** [comment]
i probably won't have time for it and maybe I am not best person to do that PR.

I just advised there maybe many more beginner developers (esp. in functional stuff) trying to use immer and they might not be well aware of the stuff we discussed.

Ok that's it. Bye thanks.

**Comment by davidmal200** [comment]
@mweststrate Also

> One of the core principles of Redux for example is that the state must be a tree as doing otherwise will break assumptions other tools make on your state

I don't see in the link you provided where Redux states that tree can't be graph e.g. that two objects can be repeated in the tree.

**Comment by mweststrate** [comment]
A tree is always a graph. But not all graphs are trees, like yours. As soon
as there are two paths leading to the same leaf, it is no longer a tree.
https://en.wikipedia.org/wiki/Tree_(graph_theory). The main reason that
normalization is an important concept when working with Redux, is to make
sure that the tree properties are preserved. As stated, you will have to
either make sure your filteredItems are denormalized, or make sure that the
filtered items are not part of the state in the first place (you could
store for example the filter itself, instead of it's resulut)

Op ma 24 sep. 2018 om 12:08 schreef davidmal200 <notifications@github.com>:

**Comment by davidmal200** [comment]
@mweststrate I think we have bit muiscommunication.

_I understand requirement of immer that state must be unidirectional tree._

However, what I said it is **not a requirement in Redux** for state to be a tree such that same object can't appear twice for example. e.g. see here: https://stackoverflow.com/questions/43657675/redux-what-is-the-point-of-normalizing-the-data#. It maybe recommendation **but not a requirement.**

**Comment by mweststrate** [comment]
I read the page as follows: the state must be a tree, that is why a lot of
data is duplicated in the examples. Since this is a bad thing, stuff should
be normalized. The normalization part is, as far as I can see the optional
part, (there are cases where non-normalized trees can be more convenient,
for example if compositional relationships are used).

The reducer model simply breaks when using a graph; try for example to
write a reducer that updates the element with ID: 1 in the state you are
proposing. You will notice that it will be very tricky to create a next
state that is still a graph, especially if you want to keep couplinglow.
but anyhow, you are free to structure your state whatever you like, but as
far as it concerns immer: it doesn't guarantee anything when using graphs.

Op ma 24 sep. 2018 om 15:41 schreef davidmal200 <notifications@github.com>:
