### ISSUE TITLE
Array values of produced Object are not frozen? Limitation or bug?

### ISSUE THREAD

**Issue by suitedjimster** [mweststrate/immer#260]
* [ ] Issue: Passing an array of objects, does not seem to deep freeze deep arrays.
  * Version: 1.8.0
  * _SIMPLE_ Reproduction: https://codesandbox.io/s/oqnrqlorj9
  * Expected behavior: All deep children object including arrays would be frozen.
  * Actual behavior:  Arrays inside an arrays of objects are not frozen and are allowed to be mutated outside of the produce function

**Comment by mweststrate** [comment]
Immer currently doesn't apply freezing to the full tree, but only to the parts which are touched by immer itself. Full tree freezing might be expensive and can be easily achieved outside immer (for example by using the `deepfreeze` package.

**Comment by aleclarson** [comment]
Objects you create in a producer are skipped by Immer during the finalization phase. You must be careful not to deep-freeze an object that contains a draft. If you're not sure, deep-freeze the object _outside_ its producer, since then you can guarantee any drafts have been swapped out.

Related: #230

**Comment by aleclarson** [comment]
The above solution can now be used in v1.9.0+
