### ISSUE TITLE
Saving nested drafts

### ISSUE THREAD

**Issue by dfadev** [mweststrate/immer#281]
* [ ] Issue: Forking nested results
  * Version: 1.9.3
  * _SIMPLE_ Reproduction: https://codesandbox.io/s/lrqmlj5pwm
  * Expected behavior:
I want to be able to save the result of a nested producer for later use.

  * Observed behavior:
Nested result is unusable once revoked by the parent producer.

  * [ x] Occurs when using Proxies (use `setUseProxies(true)`)
  * [ x] Occurs in the ES5 implementation (use `setUseProxies(false)`)

**Comment by aleclarson** [comment]
Currently, if you want a nested `produce` call to actually produce a __copy__, you must pass `state` to the `original` function export __before__ calling `produce` ([example](https://codesandbox.io/s/1vjkwpp1pj)). Otherwise, your nested producer will be mutating the same draft ([example](https://codesandbox.io/s/mo5z09nw8)).

This behavior will definitely change in the future.

**Comment by dfadev** [comment]
I want the nested producer to mutate it's parent's draft and not the original state:

https://codesandbox.io/s/v0q1ljppm0

**Comment by aleclarson** [comment]
@dfadev Oh, right. My bad!

That's not currently possible! 😞 

I might be working on a solution sometime soon. You'll find out if this gets fixed! 👍

**Comment by aleclarson** [comment]
Ah, just realized what I'm working on won't directly address your issue.

Is there a reason you can't structure your code [this way](https://codesandbox.io/s/jvj34w6l49)?

**Comment by bebbi** [comment]
@aleclarson Would you mind restoring the sandbox you're pointing to in your last comment? It seems helpful to people landing on this issue.
