### ISSUE TITLE
Idea: non-callback form of immer

### ISSUE THREAD

**Issue by mweststrate** [mweststrate/immer#302]
Occasionally I have cases where the callback based api of Immer is to limited, for example when I don't have explicit control over the flow or timing that drafts should be modified. For example in asynchronous processes where the draft should be updated bit by bit. In those cases I would like an api in which I can have more control, for example:

```javascript
import { createDraft, finishDraft } from "immer"

const todo = { title: '', done: false }

async function loadTodo() {
    const draftTodo = createDraft(todo)
    draftTodo.title = await fetchTitle()
    draftTodo.done = await fetchDone()
    todo = finishDraft(draftTodo)
}
```

**Comment by jamiewinder** [comment]
Just one idea off the back of this. Would it / might it be possible to leave the draft 'active' so you can produce multiple variants of it? For example: 
```javascript
const draft = createDraft(todo);
draft.title = 'Updated title';
const todoWithUpdatedTitle = finishDraft(draft);
draft.done = true;
const todoWithUpdatedTitleAndDone = finishDraft(draft);
```

**Comment by benjaminketron** [comment]
It would meet our needs as we would like to be able to pass a draft into asynchronous workflow logic and then finalize the draft upon workflow completion.

**Comment by aleclarson** [comment]
Note that @Yurickh's proposal would be a breaking change.

**Comment by Yurickh** [comment]
Would it, really? I mean, it looks like an extension of the current API, rather than breaking.

**Comment by aleclarson** [comment]
@Yurickh The current behavior returns the `Promise` as a replacement of the base state.

**Comment by aleclarson** [comment]
Oh, that's a great idea! I think we could support that and the OP in one fell swoop.

**Comment by jamiewinder** [comment]
If `produce` returns a Promise then all functions that use it need to be async in order to await it (or handle promises), right? Maybe I'm misunderstanding. 

I think the async example in the original post is only one of many possible use cases. The non-callback form that @mweststrate suggested is the most basic form that immer could take, and can easily be used to create `produce` and `produceAsync` variants.

**Comment by pantoninho** [comment]
I really like @Yurickh's suggestion, and I think it could be implemented without a breaking change:

// if recipe returns a promise, produce returns a promise too
const nextState = await produce(state, async (draft) => draft);

// if recipe does not return a promise, then produce is synchronous and returns the value right away.
const nextState = produce(state, draft => draft);

**Comment by aleclarson** [comment]
@pantoninho It's already implemented in #305 😉

**Comment by pantoninho** [comment]
That was fast!
Thank you, this will be very useful for me.

Great work @aleclarson and everyone involved.

**Comment by aleclarson** [comment]
Looks like async/await support __will__ be a breaking change after all. See here: https://github.com/mweststrate/immer/pull/307#issuecomment-459968964

**Comment by scriby** [comment]
I'm curious about what happens when there are multiple async draft edits going at once. It seems like after one of them has gone async the state may be modified before it picks up again, which means it's now working against an older version of state. It also seems like there's some potential for conflicts due to the async sequencing.

Am I misunderstanding, or is there a pretty good source of potential danger here if you don't understand what's going on under the covers pretty well?

**Comment by mweststrate** [comment]
I'm not sure if I understand, state is immutable, so there is no "older"
one. Maybe demonstrate with some code what you mean?

Op zo 3 feb. 2019 03:11 schreef scriby <notifications@github.com>:
