### ISSUE TITLE
Immutable type allows Dates to mutate.

### ISSUE THREAD

**Issue by nicu-chiciuc** [mweststrate/immer#318]
* [x] Issue: When using the `Immutable<T>` where T contains some Date, it is possible to call methods like `setFullYear()` which will mutate the initial date.
  * Version: 2.0.0
  * Expected behavior: There should be an error when trying to mutate an Immutable date
  * Observed behavior: No errors

We're currently using Typescript in JSDoc (with VS Code) since it's not possible to switch completely to Typescript at the moment. I've tried making the state and props of components deeply immutable so I've used ['ts-essentials'](https://github.com/krzkaczor/ts-essentials) `DeepReadonly<T>` type to do this and it worked quite well.

Below is an example of what I've managed to achieve using .d.ts files:
```javascript
export type ComponentStateMutable = {
   something: number;
  modifiedAt: Date;
}

export type ComponentState = DeepReadonly<ComponentStateMutable>;
```

Everything worked well with `produce()` except when trying to pass an draft object that contained a Date into a function that expected a `ComponentStateMutable`;
```
Property '[Symbol.toPrimitive]' is missing in type '{ toString: () => string;
toDateString: () => string; toTimeString: () => string; toLocaleString:
{ (): string; (locales?: string | string[], options?: DateTimeFormatOptions): string; };
toLocaleDateString: { ...; }; ... 37 more ...; toJSON: (key?: any) => string; }'
but required in type 'Date'
```
I didn't managed to figure out how to fix the problem with `Symbol.toPrimitive`.
Fortunately I've looked through immer's source code and found `Immutable<T>`. After switching everything from `DeepReadonly` to `Immutable` the errors disappeared but I realised that Dates are not actually immutable (because of the `AtomicObject` type).

[DeepReadonly's implementation](https://github.com/krzkaczor/ts-essentials/blob/master/lib/types.ts#L28) seems quite good because it also maintains the inner types on destructuring and I was thinking about somehow extending the `IProduce` so that when a object of type `DeepReadonly<Something>` is passed as the initial state, the draft should have a `Something` type.

Unfortunately my knowledge of Typescript is not very big and with the current situation of using JSDoc and .d.ts it's even harder to find documentation and other people that have the same issue. Any suggestion would be immensely appreciated.

**Comment by aleclarson** [comment]
The `DeepReadonly` type you mentioned only adds the `readonly` attribute to every property, which is pointless in the case of `Date` objects since they have no mutable properties to begin with (only methods that mutate their internal data). For this reason, the `Immutable` type provided by Immer avoids touching the `Date` type at all.

We *could* use a "mapped type" to remove any `Date` methods that perform mutations. This would be a breaking change, but might be worth it. If we did this, you wouldn't be able to pass the "immutable" `Date` object to any function that expects a normal `Date` type, which may or may not be a good thing. This `Immutable<Date>` type would be "leaky" in the sense that any function that expects a `Date` argument (yet never plans to mutate it) would need to use `Immutable<Date>` instead if you ever wanted to use that function from inside an Immer producer, for example. Or you would first need to cast the `Immutable<Date>` to a normal `Date` type, which would defeat the point.

IMO, the best route is to always clone a `Date` object before you perform mutations, and avoid using functions that mutate a `Date` object without first cloning it.

**Comment by aleclarson** [comment]
As a compromise, you can still achieve runtime safety by using a function like this:
```js
const mutators = Object.getOwnPropertyNames(Date.prototype).filter(name => name.startsWith('set'))

function frozenDateError() {
  throw Error('Cannot mutate a frozen date. Try cloning it first.')
}

export function freezeDate(date) {
  mutators.forEach(name => {
    date[name] = frozenDateError
  })
  return date
}
```
The only caveat is you'll need to wrap all of your `Date` objects with it.

**Comment by nicu-chiciuc** [comment]
You're right, I've missed the fact that you can still call mutable methods when using `DeepReadonly`. I think I confused this because there was an error when trying to pass a `DeepReadonlyObject<Date>` to `moment` which expected a `Date`.

Regarding the freezing, I was more interested in having some type of "compile-time" guarantees.

As a side note, I think it would be beneficial to include something like an inner `DeepReadonlyObject` (maybe called `ImmutableObject` like the `ImmutableTuple` one) so that when hovering over the definition of an immutable it could show something like:
```
(property) MyComponent.state: DeepReadonlyObject<MyComponent.MyComponentStateMutable>
```

instead of:
```
(property) MyComponent.state: {
    readonly pages: ReadonlyArray<{
        readonly _id: string;
        readonly something: string;
        readonly type: PageType;
        readonly createdAt?: string;
        readonly modifiedAt?: Date;
        readonly lastVisitedAt?: Date;
        ... 22 more ...;
        readonly where?: string;
    }>;
    ... 24 more ...;
    readonly forceUpdate: boolean;
}
```

**Comment by nicu-chiciuc** [comment]
I'm not sure if my last message required a new issue. I could try to work on it tomorrow if it seems like a reasonable problem to other people.

**Comment by nicu-chiciuc** [comment]
I've managed to temporarily solve my problems by using:
```
/**
 * @template T
 * @param {import('ts-essentials').DeepReadonly<T>} initial
 * @param {(draft: T) => void} func
 */
const produceDeep = (initial, func) => produce(initial, func);
```
