### ISSUE TITLE
Immer needs a logo!

### ISSUE THREAD

**Issue by mweststrate** [mweststrate/immer#41]

**Comment by diegochavez** [comment]
Hi Michel! I love this project, Mobx is also one of my favs! I did something simple yesterday night, let me know what do you think :)

![immer-logo](https://user-images.githubusercontent.com/35136/35034714-605e5c9a-fb6f-11e7-9de2-69d17505d388.png)

**Comment by mweststrate** [comment]
Thanks and looks neat! Will wait a while to see if more contenders show up :)

**Comment by Sventenhaaf** [comment]
In my humble opinion the infinity sign is just a must with this name... Thanks @diegochavez !

![immerlogo](https://user-images.githubusercontent.com/8081258/35707192-18098be0-07a9-11e8-9600-bdac848e9985.gif)

**Comment by Sventenhaaf** [comment]
In my humble opinion the infinity sign is a must with a name like Immer... Thanks @diegochavez!

I made a little tool in which people can adjust the colors and properties of the logo. I'm not a designer so I hope other people can jump in and pick the right colors, stroke thicknesses and all that...

![immerlogo](https://user-images.githubusercontent.com/8081258/35707322-9473a2a6-07a9-11e8-96bd-f2420912ac0b.gif)


 
**[==> Give it a try](https://envelope.li/edit/-L4IHcws4claLKuKTmWZ)!**

**Comment by diegochavez** [comment]
@mweststrate Awesome! I'll add some style to match mobx-state-tree logo like you suggest. 👍

**Comment by diegochavez** [comment]
![logo immer](https://user-images.githubusercontent.com/35136/37372383-d3400bea-2712-11e8-854f-b597c564c857.jpg)
@mweststrate hey time ago I've been quite busy but I get some time this week 👍 .

Take a look this simpler version 
![logo immer - alt](https://user-images.githubusercontent.com/35136/37372524-4b986a38-2713-11e8-8bb3-5a1f51547581.jpg)

**Comment by dwighthouse** [comment]
@mweststrate  Some recommendations:

I would recommend against shadows/gradients/transparencies in logos. Good logo design seeks to make the logo recognizable even when only one, flat color is available, such as black-on-white themed icon sets. It should also work with two to six solid colors if it isn't designed to only have a single color variant. (and remember to check these with colorblind modes)

I would recommend that, unless you plan to make a logo significantly asymmetrical, the logo should aim for some symmetry. The infinity sign above could not be bisected and mirrored horizontally or vertically and still result in the same symbol because it is very slightly asymmetrical on both axes.

Personal opinion: with the rise of SVG, designing a logo that can be efficiently expressed in SVG is a good idea, allowing logos to just be inlined to avoid round trips and network failures.

**Comment by mweststrate** [comment]
Picked the first one, also based on the comments by @dwighthouse . Thanks @diegochavez !
